# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Capstone_IBOR'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directory which will store compiled SQL files
target-path: "target"

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# --------------------------------------------------
# Model configuration
# --------------------------------------------------
models:
  Capstone_IBOR:
    # Default for all models in the project
    +materialized: view

    Bronze:
      +schema: BRONZE

    Silver:
      +schema: SILVER

    Gold:
      +schema: GOLD
